# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1naQ4ql_aacm3_O9APyoY4EgxPH6Kw5GU
"""

from flask import Flask, request, render_template
import nltk
from string import punctuation
import re
from nltk.corpus import stopwords
from flair.models import TextClassifier
from flair.data import Sentence
import sys

nltk.download('stopwords')

set(stopwords.words('english'))

## Get flair model
classifier = TextClassifier.load('en-sentiment')

app = Flask(__name__)

@app.route('/')
def my_form():
    return render_template('form.html')

@app.route('/', methods=['POST'])
def my_form_post():

    ## Get stop words
    stop_words = stopwords.words('english')
    
    ## Convert to lowercase
    text1 = request.form['text1'].lower()
    text_final = ''.join(c for c in text1 if not c.isdigit())
    
    ## Remove punctuations
    text_rmpunc = ''.join(c for c in text_final if c not in punctuation)
        
    # Remove stopwords    
    text_rmstop = ' '.join([word for word in text_rmpunc.split() if word not in stop_words])

    ## Classification
    sentence = Sentence(text_rmstop)
    classifier.predict(sentence) 

    ## Get result
    sent = str(sentence.labels[0])
    confidence = float(re.findall("\d+\.\d+", sent)[0])
    sentiment = " ".join(re.findall("[a-zA-Z]+", sent))


    return render_template('form.html', confidence=confidence, sentence=text_final, sentiment=sentiment)

if __name__ == "__main__":
    # app.run(debug=True, host="127.0.0.1", port=8000, threaded=True)
    if "serve" in sys.argv: app.run(host='0.0.0.0', port=8000, debug=False)
